### ISSUE TITLE
Can the IIndex generics be swapped?

### ISSUE THREAD

**Issue by smudge202** [dennisdoomen/FluidCaching#1]
I commented on [your blog post](http://www.continuousimprover.com/2016/02/a-least-recently-used-cache-that-you.html) but appreciate this is the correct place to post such a question.

Can the `T` / `TKey` be swapped? From using Dictionary's, most .Net developers are likely to assume `TKey` first.

**Comment by dennisdoomen** [comment]
This is solved with the merged PR, isn't it?

**Comment by smudge202** [comment]
Absolutely. I tend to let owner close (I completely forget). :laughing:

**Comment by dennisdoomen** [comment]
:+1:
