### ISSUE TITLE
Error: The bag number has reached its max value

### ISSUE THREAD

**Issue by MarcusChamberlain** [dennisdoomen/FluidCaching#39]
Occasionally while running projectors based on LiquidProjections, I receive the following error on startup:

 `System.OverflowException: The bag number has reached its max value`
`at OrderedAgeBagCollection1.get_Item(Int32 number)` 
`at LifespanManager1.CleanUp(DateTime now) `
` at LifespanManager1.CheckValidity()`

Restarting the projector clears up this error. I've poked around the FluidCaching code and nothings jumping out which could be causing this. Do you have any advice on what scenarios could lead to this error? 

It's suspected it may be a resource issue where the cache isn't able to hold the projection data and is recycling over and over on startup (since it fails in "CleanUp(DateTime now)"). Would this error occur if our cache is set too large? 

If you've designed this error for specific cases, do you have any advice on what might be triggering it?

Thanks.

**Comment by dennisdoomen** [comment]
I assume you're using LiquidProjections.NHibernate? If so, which version are you using?

**Comment by dennisdoomen** [comment]
Oh, and what values do you use for `capacity`, `minAge` and `maxAge` ?

**Comment by MarcusChamberlain** [comment]
I'm using a slightly modified version of the 'LiquidProjections.RavenDB' package. It's mostly the same except for some modifications to make it work with [Nevermore](https://github.com/OctopusDeploy/Nevermore). The 'RavenEventMapConfigurator' was replaced with 'NevermoreEventMapConfigurator', which updates the Create/Update/Delete methods to work with the Nevermore session. 

As for the settings, they are set too:
`capacity`= 5000. There are also a few low traffic child projectors which are set to 30. 
`minAge`= 30 seconds (all).
`maxAge`= 2 minutes (all).

Other notes: When the projector falls over, it seems to make it pretty far into the projections. It's usually around the 95% mark that the bag number error occurs. The memory use on the VM's running the projections hovers around 90% usage since they are just small K8 pods - this doesn't seem to cause issues with the projectors themselves, but if the VM runs out of memory while FluidCaching is adding items to the cache, could this lead to the error above?

**Comment by dennisdoomen** [comment]
Ah, that confirms my suspicion. That repo is using a version of [FluidCaching](https://github.com/liquidprojections/LiquidProjections.RavenDB/blob/master/Src/LiquidProjections.RavenDB/FluidCaching.cs) that does not contain the `StackOverflow` [fix](https://github.com/dennisdoomen/FluidCaching/pull/32) yet. I'm about to release another version of FluidCaching in the next couple of days. I'll update the corresponding LP RavenDB and NHibernate packages after that.

**Comment by dennisdoomen** [comment]
In fact, if you didn't update the FluidCaching files in `LiquidProjections.RavenDB`, it was probably still using 1.1. So in the mean time, I recommend overwriting the files with the latest FluidCaching package.

**Comment by MarcusChamberlain** [comment]
Brilliant, I'll give that a shot. Thanks for the help Dennis.

**Comment by dennisdoomen** [comment]
In the mean time, I've released updated version of `LiquidProjections.RavenDB` 3 and 4 that include the latest version of `FluidCaching`.
