### ISSUE TITLE
Dev branch please

### ISSUE THREAD

**Issue by smudge202** [dennisdoomen/FluidCaching#4]
`Contributing.md` specifies we should PR to dev, but there isn't a dev yet. :)

**Comment by dennisdoomen** [comment]
I copied that file from another project. Not sure if it makes sense to have a _develop_ branch. Until I've added all the missing unit tests, I don't think I will release the first nuget package. Thoughts?

**Comment by smudge202** [comment]
Agreed; will try help with those tests but valentines weekend so finding time might be a pain.

**Comment by dennisdoomen** [comment]
Finally created the _deveop_ branch to fix any lingering issues while using this on an actual project.
